site_name: ckanext-selfinfo

theme:
  name: material

nav:
  - Home: index.md
  - Requirements: requirements.md
  - Installation: installation.md
  - Config Settings: config_settings.md
  - Configuration:
    - Secure URL and Action: secure_url_and_action.md
    - Unique Redis key: unique_redis_key_per_portal_instance.md
    - Enable Errors: errors.md
    - GIT Info: git_info.md
    - Categories: categories.md
  - CLI: cli.md

