site_name: ckanext-selfinfo
site_url: https://datashades.github.io/ckanext-selfinfo/

repo_url:  https://github.com/DataShades/ckanext-selfinfo

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Requirements: requirements.md
  - Installation: installation.md
  - Config Settings: config_settings.md
  - Configuration:
    - Secure URL and Action: secure_url_and_action.md
    - Unique Redis key: unique_redis_key_per_portal_instance.md
    - Enable Errors: errors.md
    - GIT Info: git_info.md
    - Categories: categories.md
  - CLI: cli.md
  - Profiles:
    - Overview: profiles/overview.md
    - Cron Based:
      - Selinfo from Redis key: profiles/redis_key.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences