version: 1
groups:
    - annotation: selftools configuration
      options:
          - key: ckan.selftools.opetations_pwd
          - key: ckan.selftools.operations_limit
            type: int
            default: 100
          - key: ckan.selftools.config_blacklist
            type: list
            default: ''
          - key: ckan.selftools.categories
            type: list
            default: solr db redis config
          - key: ckan.selftools.tools_blacklist
            type: list
            default: ''
